Add push test from registered repo
kamu-data/kamu-cli pull request #907
Opened 2024-10-16 15:03 UTC by rmn-boiko

## Description

Closes: #issue

## Checklist before requesting a review

- [x] Unit and integration tests added
  
- [x] Compatibility:
    
  - [x] Network APIs: ✅
    
  - [x] Workspace layout and metadata: ✅
    
  - [x] Configuration: ✅
    
  - [x] Container images: ✅
- [x] Observability:
    
  - [x] Tracing / [metrics](https://github.com/kamu-data/kamu-standards/blob/master/metrics_design.md): ✅
    
  - [x] Alerts: ✅
- [x] Documentation:
    
  - [x] [Changelog](./CHANGELOG.md): ✅
    
  - [x] [Public documentation](https://github.com/kamu-data/kamu-docs/): ✅
  
- [x] Downstream effects:
    
  - [x] [kamu-node](https://github.com/kamu-data/kamu-node): ✅
    
  - [x] [kamu-web-ui](https://github.com/kamu-data/kamu-web-ui): ✅
    
  - [x] [release-queue](https://github.com/orgs/kamu-data/projects/4/views/1)

2024-10-16 15:13 UTC, s373r requested changes

2024-10-16 15:13 UTC, s373r commented on src/e2e/app/cli/inmem/tests/tests/test_smart_transfer_protocol.rs
> +    storage = inmem,
add sqlite, postgres variants

2024-10-16 15:23 UTC, s373r requested changes

2024-10-16 15:23 UTC, s373r commented on src/e2e/app/cli/sqlite/tests/tests/test_smart_transfer_protocol.rs
> +    storage = postgres,
sqlite

2024-10-17 12:07 UTC, s373r approved these changes

2024-10-18 07:28 UTC, zaychenko-sergei approved these changes

2024-10-18 07:28 UTC, merged